### ISSUE TITLE
I tried running the site locally and got stuck in the last step.

### ISSUE THREAD

**Issue by pjha1994** [learn-anything/learn-anything#1222]
user@user: npm start

> learn-anything-search-engine@2.0.0 start /home/user/Desktop/GIT/other/learn-anything
> node server/index.js -p 3000

/home/user/Desktop/GIT/other/learn-anything/server/helpers/maps.js:42
      ...Item,
      ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/Desktop/GIT/other/learn-anything/server/api/maps.js:3:14)

npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! learn-anything-search-engine@2.0.0 start: `node server/index.js -p 3000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the learn-anything-search-engine@2.0.0 start script 'node server/index.js -p 3000'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the learn-anything-search-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/index.js -p 3000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs learn-anything-search-engine
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls learn-anything-search-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/.npm/_logs/2017-12-03T22_50_00_971Z-debug.log

**Comment by nglgzz** [comment]
Have you tried updating node? Seems like it's complaining about object spread (those 3 dots before`Items`) and that syntax was added fairly recently, so updating should solve.

Let me know if that helps.

**Comment by pjha1994** [comment]
Thanks, that fixed the issue. Although once that I have got it running, it is not showing any paths

`npm start

> learn-anything-search-engine@2.0.0 start /home/piyush/Desktop/GIT/other/learn-anything
> node server/index.js -p 3000

Server started.
HOST_IP:  undefined
webpack: wait until bundle finished: /
webpack built afb0476d000619f1a002 in 28005ms
Hash: afb0476d000619f1a002
Version: webpack 3.6.0
Child
    Hash: afb0476d000619f1a002
    Time: 28005ms
               Asset     Size  Chunks                    Chunk Names
        en.bundle.js   3.3 MB       0  [emitted]  [big]  main
    en.bundle.js.map  3.72 MB       0  [emitted]         main
       [1] ./node_modules/react/index.js 190 bytes {0} [built]
      [14] ./node_modules/react-redux/es/index.js 230 bytes {0} [built]
      [45] ./node_modules/react-router-dom/es/index.js 925 bytes {0} [built]
      [52] (webpack)/buildin/module.js 517 bytes {0} [built]
      [58] ./node_modules/react-dom/index.js 1.36 kB {0} [built]
      [76] ./client/store/store.js 1.2 kB {0} [built]
     [249] multi webpack-hot-middleware/client?reload=true&timeout=2000 react-hot-loader/patch ./client/index.jsx 52 bytes {0} [built]
     [250] (webpack)-hot-middleware/client.js?reload=true&timeout=2000 7.04 kB {0} [built]
     [260] (webpack)-hot-middleware/process-update.js 3.87 kB {0} [built]
     [261] ./node_modules/react-hot-loader/patch.js 41 bytes {0} [built]
     [262] ./node_modules/react-hot-loader/lib/patch.js 209 bytes {0} [built]
     [371] ./client/index.jsx 2.29 kB {0} [built]
     [444] ./client/containers/Router.jsx 4.51 kB {0} [built]
     [692] ./client/utils/openNewTab.js 549 bytes {0} [built]
     [693] ./client/sass/main.sass 1.29 kB {0} [built]
        + 679 hidden modules
webpack: Compiled successfully.
[ResourceNotFoundException:400] Cannot do operations on a non-existent table
[ResourceNotFoundException:400] Cannot do operations on a non-existent table
[ResourceNotFoundException:400] Cannot do operations on a non-existent table
`

I tried a few other queries and apparently the issue is the same as in last three lines above.

**Comment by nglgzz** [comment]
I just realized we're missing one step on the readme where you add the maps on dynamodb. Running `cd maps/scripts & node dynamo/setup.js` should be sufficient (it might also take a while to run as it's loading all maps). 

In the upcoming days I'm going to do some cleaning, so hopefully getting everything set up will be much faster.

Let me know if you have more problems

**Comment by pjha1994** [comment]
What am I doing wrong here?

>cd maps/scripts && node dynamo/setup.js

{ ResourceInUseException: Cannot create preexisting table
    at Request.extractError (/home/user/Desktop/GIT/other/learn-anything/maps/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/home/user/Desktop/GIT/other/learn-anything/maps/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/user/Desktop/GIT/other/learn-anything/maps/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/user/Desktop/GIT/other/learn-anything/maps/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/user/Desktop/GIT/other/learn-anything/maps/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/user/Desktop/GIT/other/learn-anything/maps/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/user/Desktop/GIT/other/learn-anything/maps/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/user/Desktop/GIT/other/learn-anything/maps/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/user/Desktop/GIT/other/learn-anything/maps/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/user/Desktop/GIT/other/learn-anything/maps/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Cannot create preexisting table',
  code: 'ResourceInUseException',
  time: 2017-12-04T21:27:29.383Z,
  requestId: 'cfb06de3-7c2c-4566-a132-143c98ad4ba5',
  statusCode: 400,
  retryable: false,
  retryDelay: 6.0660702487280505 }

I restarted the db and the problem persisted.

**Comment by nglgzz** [comment]
Seems like it's trying to create the tables, but they're already there. Try commenting line 100 (`await mktables(Object.values(schemas));`) and run the script again

**Comment by pjha1994** [comment]
Commenting the line changes the error:

>user@user:~/Desktop/GIT/other/learn-anything/maps/scripts/dynamo$ node setup.js

{
  "TableNames": [
    "Maps",
    "Nodes",
    "Resources",
    "Votes"
  ]
}
SyntaxError: /home/user/Desktop/GIT/other/learn-anything/maps/scripts/dynamo/maps-bak.json: Unexpected token { in JSON at position 92
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:679:27)
    at Module.load (module.js:577:32)
    at tryModuleLoad (module.js:517:12)
    at Function.Module._load (module.js:509:3)
    at Module.require (module.js:608:17)
    at require (internal/module.js:11:18)
    at walkDir (/home/user/Desktop/GIT/other/learn-anything/maps/scripts/utils/dir.js:30:21)
    at walkDir.next (<anonymous>)
    at module.exports (/home/user/Desktop/GIT/other/learn-anything/maps/scripts/dynamo/saveMaps.js:86:12)

**Comment by nglgzz** [comment]
That's odd, are you on the latest commit?

**Comment by pjha1994** [comment]
I am , yes. I did a pull just to be sure. This time the same error moved from line 92 to line 109.

**Comment by nglgzz** [comment]
I started already writing the new script and that one should be much better, in any case this evening I'll have another look at this. I think that `walkDir` is trying to walk through the files in the scripts folder, although it's not supposed to do that. Can you try executing the script from the `maps` folder instead of `maps/scripts`?

**Comment by nglgzz** [comment]
Hey @pjha1994 did you manage to run the setup script?

**Comment by pjha1994** [comment]
Yes, I did try. Right now the setup runs fine. Running `npm start` gives me the following error:

user@user:~/Desktop/GIT/other/learn-anything$ npm start

> learn-anything-search-engine@2.0.0 start /home/user/Desktop/GIT/other/learn-anything
> node server/index.js -p 3000

Server started.
HOST_IP:  undefined
webpack built d60512e9358438823964 in 27558ms
Hash: d60512e9358438823964
Version: webpack 3.6.0
Child
    Hash: d60512e9358438823964
    Time: 27558ms
               Asset     Size  Chunks                    Chunk Names
        en.bundle.js   3.3 MB       0  [emitted]  [big]  main
    en.bundle.js.map  3.71 MB       0  [emitted]         main
       [1] ./node_modules/react/index.js 190 bytes {0} [built]
      [14] ./node_modules/react-redux/es/index.js 230 bytes {0} [built]
      [45] ./node_modules/react-router-dom/es/index.js 925 bytes {0} [built]
      [52] (webpack)/buildin/module.js 517 bytes {0} [built]
      [58] ./node_modules/react-dom/index.js 1.36 kB {0} [built]
      [76] ./client/store/store.js 1.2 kB {0} [built]
     [249] multi webpack-hot-middleware/client?reload=true&timeout=2000 react-hot-loader/patch ./client/index.jsx 52 bytes {0} [built]
     [250] (webpack)-hot-middleware/client.js?reload=true&timeout=2000 7.04 kB {0} [built]
     [260] (webpack)-hot-middleware/process-update.js 3.87 kB {0} [built]
     [261] ./node_modules/react-hot-loader/patch.js 41 bytes {0} [built]
     [262] ./node_modules/react-hot-loader/lib/patch.js 209 bytes {0} [built]
     [371] ./client/index.jsx 2.29 kB {0} [built]
     [444] ./client/containers/Router.jsx 4.51 kB {0} [built]
     [692] ./client/utils/openNewTab.js 549 bytes {0} [built]
     [693] ./client/sass/main.sass 1.29 kB {0} [built]
        + 679 hidden modules
    
    ERROR in ./client/constants/resource-categories.json
    Module build failed: SyntaxError: Unexpected token / in JSON at position 4
        at JSON.parse (<anonymous>)
        at Object.module.exports (/home/user/Desktop/GIT/other/learn-anything/node_modules/json-loader/index.js:4:49)
     @ ./client/components/NewResourceForm.jsx 30:26-71
     @ ./client/components/map/Node.jsx
     @ ./client/components/map/Map.jsx
     @ ./client/containers/MapPage.jsx
     @ ./client/containers/Router.jsx
     @ ./client/index.jsx
     @ multi webpack-hot-middleware/client?reload=true&timeout=2000 react-hot-loader/patch ./client/index.jsx
webpack: Failed to compile.

Apparently it was compiling fine before as we go above this conversation. We only had issue with no paths being found. But as of now I get this error part on the webpage. I googled around and tried installing `json-loader`. The problem still persists. Are there any other requirements beside node and npm to run the project?

**Comment by nglgzz** [comment]
The problem was related to one of the files (`./client/constants/resource-categories.json`) not being valid JSON, but I made a commit to fix that yesterday. Can you pull again and see if it works now? Thanks for your patience 😄

**Comment by pjha1994** [comment]
Doing pull has fixed the above issue. But the issue of finding paths still persist. Whenever I enter a query, for which I get a few suggestions as well, it is not able to show any paths.

**Comment by nglgzz** [comment]
Do you get any errors at all? Either on the terminal where you launched the app, or on the browser console?

**Comment by pjha1994** [comment]
Nope, no error this time. 

user@user:~/Desktop/GIT/other/learn-anything$ npm start

> learn-anything-search-engine@2.0.0 start /home/user/Desktop/GIT/other/learn-anything
> node server/index.js -p 3000

Server started.
HOST_IP:  undefined
webpack built 75affd56cfb5ff09c7c1 in 33204ms
Hash: 75affd56cfb5ff09c7c1
Version: webpack 3.6.0
Child
    Hash: 75affd56cfb5ff09c7c1
    Time: 33204ms
               Asset     Size  Chunks                    Chunk Names
        en.bundle.js   3.3 MB       0  [emitted]  [big]  main
    en.bundle.js.map  3.72 MB       0  [emitted]         main
       [1] ./node_modules/react/index.js 190 bytes {0} [built]
      [14] ./node_modules/react-redux/es/index.js 230 bytes {0} [built]
      [45] ./node_modules/react-router-dom/es/index.js 925 bytes {0} [built]
      [52] (webpack)/buildin/module.js 517 bytes {0} [built]
      [58] ./node_modules/react-dom/index.js 1.36 kB {0} [built]
      [76] ./client/store/store.js 1.2 kB {0} [built]
     [249] multi webpack-hot-middleware/client?reload=true&timeout=2000 react-hot-loader/patch ./client/index.jsx 52 bytes {0} [built]
     [250] (webpack)-hot-middleware/client.js?reload=true&timeout=2000 7.04 kB {0} [built]
     [260] (webpack)-hot-middleware/process-update.js 3.87 kB {0} [built]
     [261] ./node_modules/react-hot-loader/patch.js 41 bytes {0} [built]
     [262] ./node_modules/react-hot-loader/lib/patch.js 209 bytes {0} [built]
     [371] ./client/index.jsx 2.29 kB {0} [built]
     [444] ./client/containers/Router.jsx 4.51 kB {0} [built]
     [692] ./client/utils/openNewTab.js 549 bytes {0} [built]
     [693] ./client/sass/main.sass 1.29 kB {0} [built]
        + 679 hidden modules
webpack: Compiled successfully.

Everything looks fine here. No errors. The website is up. I start getting suggestions as I type in the search, but no paths afterwards.

**Comment by liamcloss** [comment]
I'm experincing the same issue here - http://doublebonus.co.uk:3000/life/work/freelancing

**Comment by nglgzz** [comment]
@liamcloss: I just tried the link you sent and seems like the tables do not exist.
![image](https://user-images.githubusercontent.com/13448636/33799402-296f8f04-dd2b-11e7-9a34-1ae59ee51348.png)
![image](https://user-images.githubusercontent.com/13448636/33799412-593f8cb6-dd2b-11e7-8dde-393e0b9d27a7.png)

@pjha1994 @liamcloss: Today I finished rewriting the setup scripts. Can you try pulling the changes, starting DynamoDB and ElasticSearch and then running `npm run setup`? That should load all maps, nodes, and resources.

**Comment by pjha1994** [comment]
So, I started from scratch again. First issue I came across was with no `aws-sdk` present which got resolved doing `npm install sdk`, which I think should be mentioned somewhere.

After running the `npm run setup`, which populated the data, I got the following messages(the tables did get populated):
`
(node:27781) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: ENOENT: no such file or directory, open '/home/user/Desktop/GIT/other/learn-anything/maps/scripts/maps-bak.json'
(node:27781) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27781) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: ENOENT: no such file or directory, open '/home/user/Desktop/GIT/other/learn-anything/maps/scripts/nodes-bak.json'
(node:27781) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: ENOENT: no such file or directory, open '/home/user/Desktop/GIT/other/learn-anything/maps/scripts/resources-bak.json'
(node:27781) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: ENOENT: no such file or directory, open '/home/user/Desktop/GIT/other/learn-anything/maps/scripts/votes-bak.json'
`

The site ran finally. But still with no paths. I tried hitting the API endpoints, just to be sure if the tables have any data:

`http://localhost:3000/api/maps` : `[{"title":"/software/tooling/text-editors/sublime-text","key":"sublime text editor","id":"1818"}]`

`http://localhost:3000/api/maps/1818` : `{"nodes":{},"resources":{}}`

`http://localhost:3000/api/maps/path/to/map` :`{"msg":"map not found"}`

It looks like the last two are not working. There are no paths showing up as of now.

**Comment by nglgzz** [comment]
> So, I started from scratch again. First issue I came across was with no aws-sdk present which got resolved doing npm install sdk, which I think should be mentioned somewhere.

You're totally right, I forgot about it, I added it now.

I realized the paths for the data files were wrong on the DynamoDB script, and it's now fixed. Basically what happened is that the script created the tables, tried to find the files for loading the data, but failed doing that. On the elasticsearch script the path was correct, so that worked and that's why you were getting suggestions, but the maps didn't show.

You can pull and run the `npm run setup` script again, that should do it :)

**Comment by pjha1994** [comment]
I am getting the following repeatedly:

Done in 2m 21s

> learn-anything-search-engine@2.0.0 setup:dynamo /home/piyush/Desktop/GIT/other/learn-anything
> node maps/scripts/dynamo/setup.js

[DS] Writing 14 elements on Maps
[DS] Writing 25 elements on Nodes
[DS] Writing 23 elements on Resources
[DS] BatchWriteItem processed all items
[DS] Writing 14 elements on Maps
[DS] BatchWriteItem processed all items
[DS] Writing 25 elements on Nodes
[DS] BatchWriteItem processed all items
[DS] Writing 23 elements on Resources
[DS] BatchWriteItem processed all items
[DS] Writing 14 elements on Maps
[DS] BatchWriteItem processed all items
[DS] Writing 14 elements on Maps
[DS] BatchWriteItem processed all items
[DS] Writing 23 elements on Resources
[DS] BatchWriteItem processed all items
[DS] Writing 25 elements on Nodes
[DS] BatchWriteItem processed all items

Is this a normal behaviour? It is going on for a while, after doing the data part on `npm run setup`

**Comment by nglgzz** [comment]
Yep it's normal, it's writing the maps, nodes and resources on DynamoDB

**Comment by pjha1994** [comment]
Thank you. The recent pull fixed all the issues. It has started showing paths. Thank you for being so patient. You guys are awesome.

**Comment by nglgzz** [comment]
Thank you for being so patient 😄
